### ISSUE TITLE
#singleton decorator

### ISSUE THREAD

**Issue by GiovanniCardamone** [Symone95/decoratorutilities#3]
Behaivour

il decoratore @singleton deve far si che una classe diventi un instanza singleton senza possibilita' di reinstanziarla

Example:

@singleton()
class X:
  x = 10

X.x => 10

**Comment by GiovanniCardamone** [comment]
commit 9aa9aae95b02b547f4fae200fde1cce8f46bca33

**Comment by Symone95** [comment]
Ciao @GiovanniCardamone,
ho aggiunto il decoratore singleton nel commit 6654ba7a0ff3710967f8438d28946b1d85a5db2e e ovviamente già testato e relativa documentazione, sia README che readthedocs.

Quando hai tempo dacci un'occhiata per favore e dimmi se va bene

Grazie

Simone

**Comment by GiovanniCardamone** [comment]
must pass this testcases before merge

- [ ] test_singleton_array_access

- [ ] test_decorating_function_must_fails

- [ ] test_accessing_property_str

- [ ] test_accessing_property_repr

- [ ] test_args_and_kwargs

**Comment by GiovanniCardamone** [comment]
Aggiungere il supporto per:

- [ ]  `__enter__` 

- [ ]  `__exit__`
