### ISSUE TITLE
cambiare nome decoratore da #cached a #memoized

### ISSUE THREAD

**Issue by GiovanniCardamone** [Symone95/decoratorutilities#8]

**Comment by GiovanniCardamone** [comment]
Mi sono accorto che il nome `cached` non rispecchia a pieno la funzione del decoratore. Un nome migliore sarebbe `memoized`

**Comment by Symone95** [comment]
Ciao @GiovanniCardamone,
ho rinominato il decoratore cached a memoized, sia nella classe che nei vari test e nella documentazione(Readme e Readthedocs)

Simone

**Comment by GiovanniCardamone** [comment]
Ricordati sempre di usare il meccanismo delle pull-request
